"""
IBVAP - Member 2 ANPR Module - schemas.py

Pydantic models that define ALL data contracts for the ANPR pipeline.
These are the ONLY types that should cross module boundaries.

Member 3 (Backend) should consume IBVAPEvent objects -- never internal
implementation classes such as PlateDetector or OCREngine.
"""

from __future__ import annotations

import enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Event types (subset owned by Member 2)
# ---------------------------------------------------------------------------

class EventType(str, enum.Enum):
    """Supported IBVAP event types.

    Only ANPR_DETECTED and WATCHLIST_MATCH are generated by Member 2.
    Other values are listed here so that the schema is self-documenting
    and consistent with the shared contract.
    """
    OBJECT_DETECTED = "OBJECT_DETECTED"
    VEHICLE_DETECTED = "VEHICLE_DETECTED"
    PERSON_DETECTED = "PERSON_DETECTED"
    ANPR_DETECTED = "ANPR_DETECTED"
    INTRUSION_DETECTED = "INTRUSION_DETECTED"
    WATCHLIST_MATCH = "WATCHLIST_MATCH"
    SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY"


# ---------------------------------------------------------------------------
# Internal pipeline data models
# ---------------------------------------------------------------------------

class PlateRegion(BaseModel):
    """Bounding-box region returned by a PlateDetector."""

    x1: int = Field(..., description="Left pixel coordinate")
    y1: int = Field(..., description="Top pixel coordinate")
    x2: int = Field(..., description="Right pixel coordinate")
    y2: int = Field(..., description="Bottom pixel coordinate")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Detection confidence [0, 1]")

    @field_validator("x1", "x2", "y1", "y2")
    @classmethod
    def coordinates_non_negative(cls, v: int) -> int:
        if v < 0:
            raise ValueError("Coordinates must be non-negative")
        return v

    @property
    def width(self) -> int:
        return self.x2 - self.x1

    @property
    def height(self) -> int:
        return self.y2 - self.y1

    @property
    def area(self) -> int:
        return self.width * self.height


class OCRResult(BaseModel):
    """Result produced by an OCREngine."""

    raw_text: str = Field(..., description="Raw OCR text before normalisation")
    confidence: float = Field(..., ge=0.0, le=1.0, description="OCR confidence [0, 1]")
    engine: str = Field(default="unknown", description="Name of the OCR engine used")


class RecognitionResult(BaseModel):
    """Normalised plate recognition result."""

    plate_number: str = Field(..., description="Normalised plate text (e.g. TN09AB1234)")
    raw_text: str = Field(..., description="Raw OCR text before normalisation")
    confidence: float = Field(..., ge=0.0, le=1.0)
    normalised: bool = Field(default=True)
    validation_passed: bool = Field(default=True, description="Whether the plate format passed validation")
    validation_reason: Optional[str] = Field(default=None, description="Validation description or pattern matched")


class WatchlistResult(BaseModel):
    """Result of a watchlist lookup."""

    plate_number: str
    is_match: bool = Field(default=False)
    status: Optional[str] = Field(default=None, description="e.g. WATCHLIST, STOLEN, WANTED")
    reason: Optional[str] = Field(default=None)


# ---------------------------------------------------------------------------
# Top-level output contract
# ---------------------------------------------------------------------------

class IBVAPEvent(BaseModel):
    """
    Common IBVAP event schema.

    This is the primary object that Member 3 (Backend) should consume.
    The backend should NOT import PlateDetector, OCREngine, or any other
    internal class -- only IBVAPEvent.
    """

    camera_id: str = Field(..., description="Identifier of the originating camera")
    event_type: EventType = Field(..., description="Categorised event type")
    timestamp: str = Field(..., description="ISO-8601 timestamp")
    confidence: float = Field(..., ge=0.0, le=1.0)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    @field_validator("camera_id")
    @classmethod
    def camera_id_non_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("camera_id must not be empty")
        return v.strip()


class ANPRResult(BaseModel):
    """
    Aggregated result of a single ANPR pipeline run on one plate in a frame.

    This is the object returned by ANPRPipeline.process_frame().
    """

    plate_number: Optional[str] = Field(default=None)
    plate_confidence: Optional[float] = Field(default=None, ge=0.0, le=1.0)
    ocr_confidence: Optional[float] = Field(default=None, ge=0.0, le=1.0)
    vehicle_id: Optional[str] = Field(default=None, description="Associated vehicle tracking ID if provided")
    watchlist_match: bool = Field(default=False)
    watchlist_status: Optional[str] = Field(default=None)
    watchlist_reason: Optional[str] = Field(default=None)
    event: Optional[IBVAPEvent] = Field(default=None)
    error: Optional[str] = Field(default=None, description="Set when pipeline encountered an error")

    @property
    def success(self) -> bool:
        """True when a plate was detected and recognised without errors."""
        return self.plate_number is not None and self.error is None
