import React, { useEffect, useState } from 'react';
import { PageHeader } from '../components/common/PageHeader';
import { Card } from '../components/common/Card';
import { LoadingSpinner } from '../components/common/LoadingSpinner';
import { detectionsService } from '../services/detectionsService';
import { Detection } from '../types/detection';
import { formatTimestamp, formatConfidence } from '../utils/formatters';
import { Search, Scan, Layers } from 'lucide-react';

export const DetectionsPage: React.FC = () => {
  const [detections, setDetections] = useState<Detection[]>([]);
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    async function loadDetections() {
      setLoading(true);
      try {
        const data = await detectionsService.getDetections();
        setDetections(data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    loadDetections();
  }, []);

  if (loading) return <LoadingSpinner label="Loading Computer Vision Object Detections..." />;

  return (
    <div className="space-y-6 animate-fadeIn">
      <PageHeader
        title="Computer Vision Detections Feed"
        subtitle="Live bounding box predictions generated by Member 1 YOLOv8 model"
        icon={<Search size={22} />}
      />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {detections.map((det) => (
          <Card key={det.id} className="p-4 flex flex-col justify-between space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="p-1.5 rounded-lg bg-cyan-500/10 text-cyan-400 border border-cyan-500/20">
                  <Scan size={16} />
                </span>
                <span className="font-bold text-sm text-slate-100">{det.object_class}</span>
              </div>
              <span className="px-2 py-0.5 bg-slate-900 border border-slate-800 text-cyan-400 font-mono font-bold text-xs rounded">
                {formatConfidence(det.confidence)}
              </span>
            </div>

            {/* Bounding Box Simulation Visual */}
            <div className="relative aspect-video bg-[#0a0d14] rounded-lg border border-slate-800 p-3 flex flex-col justify-between overflow-hidden">
              <div className="flex items-center justify-between text-[11px] font-mono text-slate-400 z-10">
                <span>{det.camera_name} ({det.camera_id})</span>
                <span>{formatTimestamp(det.timestamp)}</span>
              </div>

              {/* Bounding Box Outline Visual Graphic */}
              <div className="absolute inset-6 border-2 border-dashed border-cyan-400 rounded p-1 flex items-start justify-start bg-cyan-500/5">
                <span className="text-[9px] font-mono bg-cyan-500 text-black font-bold px-1 rounded">
                  {det.object_class} [{det.bbox.width}x{det.bbox.height}]
                </span>
              </div>

              <div className="text-[11px] font-mono text-slate-400 z-10 flex items-center justify-between">
                <span>BBOX: x:{det.bbox.x}, y:{det.bbox.y}</span>
                <span className="text-emerald-400">{det.details || 'Confidence High'}</span>
              </div>
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
};
