import React, { useEffect, useState } from 'react';
import { PageHeader } from '../components/common/PageHeader';
import { Card } from '../components/common/Card';
import { SkeletonLoader } from '../components/common/SkeletonLoader';
import { detectionsService } from '../services/detectionsService';
import { Detection, ObjectCategory } from '../types/detection';
import { formatTimestamp, formatConfidence } from '../utils/formatters';
import { Search, Scan, Tag, Filter, ShieldCheck, Car, User, Truck } from 'lucide-react';

export const DetectionsPage: React.FC = () => {
  const [detections, setDetections] = useState<Detection[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [selectedCategory, setSelectedCategory] = useState<string>('ALL');

  useEffect(() => {
    async function loadDetections() {
      setLoading(true);
      try {
        const data = await detectionsService.getDetections();
        setDetections(data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    loadDetections();
  }, []);

  const filteredDetections = selectedCategory === 'ALL'
    ? detections
    : detections.filter(d => d.object_class.toLowerCase() === selectedCategory.toLowerCase());

  const getCategoryIcon = (category: ObjectCategory) => {
    switch (category) {
      case 'person':
        return <User size={16} className="text-emerald-400" />;
      case 'truck':
        return <Truck size={16} className="text-amber-400" />;
      case 'vehicle':
      case 'car':
      case 'motorcycle':
        return <Car size={16} className="text-cyan-400" />;
      default:
        return <Scan size={16} className="text-blue-400" />;
    }
  };

  if (loading) return <SkeletonLoader type="card" count={4} />;

  return (
    <div className="space-y-6 animate-fadeIn">
      <PageHeader
        title="Computer Vision Object Detections Feed"
        subtitle="Live bounding box predictions & tracking IDs generated by Member 1 YOLOv8 model"
        icon={<Search size={22} />}
      />

      {/* Object Class Category Filters */}
      <div className="flex items-center gap-2 pb-2 overflow-x-auto">
        <span className="text-xs text-slate-400 font-mono flex items-center gap-1">
          <Filter size={14} /> Object Class:
        </span>
        {['ALL', 'person', 'car', 'truck', 'motorcycle', 'license_plate'].map((cat) => (
          <button
            key={cat}
            onClick={() => setSelectedCategory(cat)}
            className={`px-3 py-1 rounded-lg text-xs font-mono font-medium transition-all ${
              selectedCategory === cat
                ? 'bg-cyan-500 text-black font-bold shadow-md shadow-cyan-500/20'
                : 'bg-[#121824] text-slate-400 border border-slate-800 hover:border-slate-700 hover:text-slate-200'
            }`}
          >
            {cat}
          </button>
        ))}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {filteredDetections.map((det) => (
          <Card key={det.id} className="p-4 flex flex-col justify-between space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="p-1.5 rounded-lg bg-slate-900 border border-slate-800">
                  {getCategoryIcon(det.object_class)}
                </span>
                <div>
                  <span className="font-bold text-sm text-slate-100 uppercase tracking-wide font-mono">
                    {det.object_class}
                  </span>
                  <div className="text-[10px] font-mono text-cyan-400">
                    Tracking ID: <strong>{det.tracking_id}</strong>
                  </div>
                </div>
              </div>

              <span className="px-2 py-0.5 bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 font-mono font-bold text-xs rounded">
                {formatConfidence(det.confidence)}
              </span>
            </div>

            {/* Bounding Box Simulation Visual */}
            <div className="relative aspect-video bg-[#0a0d14] rounded-lg border border-slate-800 p-3 flex flex-col justify-between overflow-hidden">
              <div className="flex items-center justify-between text-[11px] font-mono text-slate-400 z-10">
                <span>{det.camera_name} ({det.camera_id})</span>
                <span>{formatTimestamp(det.timestamp)}</span>
              </div>

              {/* Bounding Box Outline Graphic */}
              <div className="absolute inset-6 border-2 border-dashed border-cyan-400 rounded p-1 flex flex-col justify-between bg-cyan-500/5">
                <span className="text-[9px] font-mono bg-cyan-500 text-black font-bold px-1 rounded inline-block self-start">
                  {det.object_class} ({det.tracking_id})
                </span>
                <span className="text-[9px] font-mono text-cyan-300 bg-black/80 px-1 rounded self-end">
                  BBOX: [{det.bbox.width}x{det.bbox.height}]
                </span>
              </div>

              <div className="text-[11px] font-mono text-slate-400 z-10 flex items-center justify-between">
                <span>Ref: {det.event_reference_id || 'EVT-AUTO'}</span>
                <span className="text-emerald-400 font-semibold">{det.details || 'YOLOv8 Confirmed'}</span>
              </div>
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
};
