import React, { useEffect, useState } from 'react';
import { PageHeader } from '../components/common/PageHeader';
import { Card } from '../components/common/Card';
import { Modal } from '../components/common/Modal';
import { SkeletonLoader } from '../components/common/SkeletonLoader';
import { eventsService } from '../services/eventsService';
import { Event, EventType } from '../types/event';
import { formatTimestamp, formatConfidence, getEventTypeBadge } from '../utils/formatters';
import { Activity, Filter, Code, Search } from 'lucide-react';

export const EventsPage: React.FC = () => {
  const [events, setEvents] = useState<Event[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [selectedType, setSelectedType] = useState<EventType | 'ALL'>('ALL');
  const [selectedCamera, setSelectedCamera] = useState<string>('ALL');
  const [selectedEvent, setSelectedEvent] = useState<Event | null>(null);

  useEffect(() => {
    async function loadEvents() {
      setLoading(true);
      try {
        const res = await eventsService.getEvents({
          event_type: selectedType,
          camera_id: selectedCamera,
        });
        setEvents(res.data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    loadEvents();
  }, [selectedType, selectedCamera]);

  const filteredEvents = events.filter((evt) => {
    if (!searchQuery) return true;
    const query = searchQuery.toLowerCase();
    return (
      evt.camera_id.toLowerCase().includes(query) ||
      evt.event_type.toLowerCase().includes(query) ||
      (evt.metadata?.license_plate && String(evt.metadata.license_plate).toLowerCase().includes(query)) ||
      (evt.metadata?.details && String(evt.metadata.details).toLowerCase().includes(query))
    );
  });

  const eventTypesList: (EventType | 'ALL')[] = [
    'ALL',
    'OBJECT_DETECTED',
    'VEHICLE_DETECTED',
    'PERSON_DETECTED',
    'ANPR_DETECTED',
    'INTRUSION_DETECTED',
    'WATCHLIST_MATCH',
    'SUSPICIOUS_ACTIVITY',
  ];

  return (
    <div className="space-y-6 animate-fadeIn">
      <PageHeader
        title="Surveillance Events Registry"
        subtitle="Historical and real-time event stream logs generated by OpenCV, YOLOv8, and ANPR modules"
        icon={<Activity size={22} />}
      />

      {/* Controls Bar: Search & Filters */}
      <div className="flex flex-col md:flex-row items-stretch md:items-center justify-between gap-4">
        {/* Search Bar */}
        <div className="relative flex-1">
          <Search size={16} className="absolute left-3 top-3 text-slate-400" />
          <input
            type="text"
            placeholder="Search by Camera ID, License Plate, or Event details..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-[#121824] border border-slate-800 rounded-xl pl-9 pr-4 py-2 text-xs font-mono text-slate-200 placeholder:text-slate-500 focus:outline-none focus:border-cyan-500 transition-colors"
          />
        </div>

        {/* Camera Select Filter */}
        <div className="flex items-center gap-2">
          <select
            value={selectedCamera}
            onChange={(e) => setSelectedCamera(e.target.value)}
            className="bg-[#121824] border border-slate-800 text-xs font-mono text-slate-200 rounded-xl px-3 py-2 focus:outline-none focus:border-cyan-500"
          >
            <option value="ALL">All Cameras</option>
            <option value="CAM-01">CAM-01 (North Gate)</option>
            <option value="CAM-02">CAM-02 (Perimeter South)</option>
            <option value="CAM-03">CAM-03 (Checkpoint Bravo)</option>
            <option value="CAM-04">CAM-04 (East Watchtower)</option>
            <option value="CAM-05">CAM-05 (West Thermal)</option>
          </select>
        </div>
      </div>

      {/* Event Type Filter Tabs */}
      <div className="flex flex-wrap items-center gap-2 pb-2 overflow-x-auto">
        <span className="text-xs text-slate-400 font-mono flex items-center gap-1 mr-1">
          <Filter size={14} /> Type:
        </span>
        {eventTypesList.map((type) => (
          <button
            key={type}
            onClick={() => setSelectedType(type)}
            className={`px-3 py-1 rounded-lg text-xs font-mono font-medium transition-all ${
              selectedType === type
                ? 'bg-cyan-500 text-black font-bold shadow-md shadow-cyan-500/20'
                : 'bg-[#121824] text-slate-400 border border-slate-800 hover:border-slate-700 hover:text-slate-200'
            }`}
          >
            {type}
          </button>
        ))}
      </div>

      {/* Events Table Container */}
      <Card className="p-0 overflow-hidden">
        {loading ? (
          <SkeletonLoader type="table-row" count={5} />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-900/90 text-[11px] font-mono text-slate-400 uppercase tracking-wider border-b border-slate-800">
                  <th className="py-3 px-4">Event ID / Camera</th>
                  <th className="py-3 px-4">Event Type</th>
                  <th className="py-3 px-4">Confidence</th>
                  <th className="py-3 px-4">Metadata Context</th>
                  <th className="py-3 px-4">Timestamp</th>
                  <th className="py-3 px-4 text-right">Payload</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60 text-xs">
                {filteredEvents.map((evt, idx) => {
                  const badge = getEventTypeBadge(evt.event_type);
                  return (
                    <tr key={evt.id || idx} className="hover:bg-slate-800/30 transition-colors">
                      <td className="py-3 px-4 font-mono font-semibold text-cyan-400">
                        <div>{evt.id || `EVT-${1000 + idx}`}</div>
                        <div className="text-[10px] text-slate-500 font-normal">{evt.camera_id}</div>
                      </td>

                      <td className="py-3 px-4">
                        <span
                          className={`inline-block text-[10px] font-mono font-bold px-2 py-0.5 rounded border ${badge.bg} ${badge.text} ${badge.border}`}
                        >
                          {evt.event_type}
                        </span>
                      </td>

                      <td className="py-3 px-4 font-mono font-bold text-slate-200">
                        {formatConfidence(evt.confidence)}
                      </td>

                      <td className="py-3 px-4 text-slate-300 font-mono text-[11px] max-w-md truncate">
                        {evt.metadata?.license_plate
                          ? `Plate: ${evt.metadata.license_plate}`
                          : evt.metadata?.details
                          ? String(evt.metadata.details)
                          : JSON.stringify(evt.metadata)}
                      </td>

                      <td className="py-3 px-4 text-slate-400 font-mono text-[11px]">
                        {formatTimestamp(evt.timestamp)}
                      </td>

                      <td className="py-3 px-4 text-right">
                        <button
                          onClick={() => setSelectedEvent(evt)}
                          className="p-1.5 bg-slate-900 hover:bg-slate-800 text-slate-300 hover:text-cyan-400 rounded-lg border border-slate-800 transition-colors"
                          title="View JSON metadata"
                        >
                          <Code size={15} />
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </Card>

      {/* JSON Payload Inspection Modal */}
      {selectedEvent && (
        <Modal
          isOpen={!!selectedEvent}
          onClose={() => setSelectedEvent(null)}
          title={`Raw Event Contract Payload (${selectedEvent.event_type})`}
        >
          <div className="space-y-3">
            <div className="p-3 bg-slate-900 rounded-lg border border-slate-800 flex items-center justify-between text-xs font-mono">
              <span className="text-cyan-400 font-bold">{selectedEvent.camera_id}</span>
              <span className="text-emerald-400">{formatConfidence(selectedEvent.confidence)} Match</span>
            </div>
            <pre className="p-4 bg-[#0a0d14] rounded-lg text-xs font-mono text-cyan-300 border border-slate-800 overflow-x-auto">
              {JSON.stringify(selectedEvent, null, 2)}
            </pre>
          </div>
        </Modal>
      )}
    </div>
  );
};
