import React, { useEffect, useState } from 'react';
import { PageHeader } from '../components/common/PageHeader';
import { Card } from '../components/common/Card';
import { Modal } from '../components/common/Modal';
import { LoadingSpinner } from '../components/common/LoadingSpinner';
import { eventsService } from '../services/eventsService';
import { Event, EventType } from '../types/event';
import { formatTimestamp, formatConfidence, getEventTypeBadge } from '../utils/formatters';
import { Activity, Filter, Eye, Code, ShieldAlert } from 'lucide-react';

export const EventsPage: React.FC = () => {
  const [events, setEvents] = useState<Event[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [selectedType, setSelectedType] = useState<EventType | 'ALL'>('ALL');
  const [selectedEvent, setSelectedEvent] = useState<Event | null>(null);

  useEffect(() => {
    async function loadEvents() {
      setLoading(true);
      try {
        const data = await eventsService.getEvents({ event_type: selectedType });
        setEvents(data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    loadEvents();
  }, [selectedType]);

  const eventTypesList: (EventType | 'ALL')[] = [
    'ALL',
    'OBJECT_DETECTED',
    'VEHICLE_DETECTED',
    'PERSON_DETECTED',
    'ANPR_DETECTED',
    'INTRUSION_DETECTED',
    'WATCHLIST_MATCH',
    'SUSPICIOUS_ACTIVITY',
  ];

  return (
    <div className="space-y-6 animate-fadeIn">
      <PageHeader
        title="Surveillance Events Registry"
        subtitle="Historical and real-time logs generated by computer vision and ANPR modules"
        icon={<Activity size={22} />}
      />

      {/* Filter Tabs */}
      <div className="flex flex-wrap items-center gap-2 pb-2 overflow-x-auto">
        <span className="text-xs text-slate-400 font-mono flex items-center gap-1 mr-2">
          <Filter size={14} /> Filter Event Type:
        </span>
        {eventTypesList.map((type) => (
          <button
            key={type}
            onClick={() => setSelectedType(type)}
            className={`px-3 py-1 rounded-lg text-xs font-mono font-medium transition-all ${
              selectedType === type
                ? 'bg-cyan-500 text-black font-bold shadow-md shadow-cyan-500/20'
                : 'bg-[#121824] text-slate-400 border border-slate-800 hover:border-slate-700 hover:text-slate-200'
            }`}
          >
            {type}
          </button>
        ))}
      </div>

      {/* Events Table Container */}
      <Card className="p-0 overflow-hidden">
        {loading ? (
          <LoadingSpinner label="Fetching event registry records..." />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-900/90 text-[11px] font-mono text-slate-400 uppercase tracking-wider border-b border-slate-800">
                  <th className="py-3 px-4">Event ID / Camera</th>
                  <th className="py-3 px-4">Type</th>
                  <th className="py-3 px-4">Confidence</th>
                  <th className="py-3 px-4">Metadata Payload</th>
                  <th className="py-3 px-4">Timestamp</th>
                  <th className="py-3 px-4 text-right">Inspect</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60 text-xs">
                {events.map((evt, idx) => {
                  const badge = getEventTypeBadge(evt.event_type);
                  return (
                    <tr key={evt.id || idx} className="hover:bg-slate-800/30 transition-colors">
                      <td className="py-3 px-4 font-mono font-semibold text-cyan-400">
                        <div>{evt.id || `EVT-${1000 + idx}`}</div>
                        <div className="text-[10px] text-slate-500 font-normal">{evt.camera_id}</div>
                      </td>

                      <td className="py-3 px-4">
                        <span
                          className={`inline-block text-[10px] font-mono font-bold px-2 py-0.5 rounded border ${badge.bg} ${badge.text} ${badge.border}`}
                        >
                          {evt.event_type}
                        </span>
                      </td>

                      <td className="py-3 px-4 font-mono font-bold text-slate-200">
                        {formatConfidence(evt.confidence)}
                      </td>

                      <td className="py-3 px-4 text-slate-300 font-mono text-[11px] max-w-md truncate">
                        {evt.metadata?.license_plate
                          ? `Plate: ${evt.metadata.license_plate}`
                          : evt.metadata?.details
                          ? String(evt.metadata.details)
                          : JSON.stringify(evt.metadata)}
                      </td>

                      <td className="py-3 px-4 text-slate-400 font-mono text-[11px]">
                        {formatTimestamp(evt.timestamp)}
                      </td>

                      <td className="py-3 px-4 text-right">
                        <button
                          onClick={() => setSelectedEvent(evt)}
                          className="p-1.5 bg-slate-900 hover:bg-slate-800 text-slate-300 hover:text-cyan-400 rounded-lg border border-slate-800 transition-colors"
                          title="View JSON metadata"
                        >
                          <Code size={15} />
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </Card>

      {/* JSON Payload Inspection Modal */}
      {selectedEvent && (
        <Modal
          isOpen={!!selectedEvent}
          onClose={() => setSelectedEvent(null)}
          title={`Raw Event Contract Payload (${selectedEvent.event_type})`}
        >
          <div className="space-y-3">
            <div className="p-3 bg-slate-900 rounded-lg border border-slate-800 flex items-center justify-between text-xs font-mono">
              <span className="text-cyan-400 font-bold">{selectedEvent.camera_id}</span>
              <span className="text-emerald-400">{formatConfidence(selectedEvent.confidence)} Match</span>
            </div>
            <pre className="p-4 bg-[#0a0d14] rounded-lg text-xs font-mono text-cyan-300 border border-slate-800 overflow-x-auto">
              {JSON.stringify(selectedEvent, null, 2)}
            </pre>
          </div>
        </Modal>
      )}
    </div>
  );
};
